# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - caballeroApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set lower case registry username
      run: |
        echo "REGISTRY_USERNAME_LC=${REGISTRY_USERNAME,,}" >>${GITHUB_ENV}
      env:
        REGISTRY_USERNAME: '${{ secrets.AzureAppService_ContainerUsername_28ad50ecfd6c484981064715ddedf7be }}'

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://caballeroregistry.azurecr.io/
        username: ${{ env.REGISTRY_USERNAME_LC }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6026a196354648daa902ed72bce38605 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: caballeroregistry.azurecr.io/webimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'caballeroApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fa1e66b4c09e4bebadc3635241c6c898 }}
        images: 'caballeroregistry.azurecr.io/webimage:${{ github.sha }}'
